[package]
name = "darude"
version = "0.1.0"
authors = ["Will Greenberg <ifnspifn@gmail.com>"]

[lib]
name = "darude"
path = "src/lib.rs"

[[bin]]
name = "cardioids"
path = "examples/cardioids.rs"

[dependencies]
rand = "0.3"
rayon = "0.9.0"
